[package]
name = "setodo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { git = "https://github.com/emilk/egui.git" }
rmp-serde = "1.0.0"
dirs = "4.0.0"
rfd = "0.8.1"
open = "2.1.1"
zstd = "0.11.1"

[dependencies.serde]
version = "1.0.136"
features = ["derive"]
