[package]
name = "setodo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.22.0", features = ["persistence"] }
rmp-serde = "1.1.2"
dirs = "5.0.1"
rfd = "0.11.4"
open = "5.0.0"
zstd = "0.12.4"

[dependencies.serde]
version = "1.0.183"
features = ["derive"]
