[package]
name = "setodo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { git = "https://github.com/emilk/egui.git" }
rmp-serde = "1.0.0-beta.2"
dirs = "4.0.0"
rfd = "0.6.3"
open = "2.0.2"
zstd = "0.9.1"

[dependencies.serde]
version = "1.0.132"
features = ["derive"]
