[package]
name = "setodo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.22.0", features = ["persistence"] }
rmp-serde = "1.1.0"
dirs = "4.0.0"
rfd = "0.8.2"
open = "2.1.2"
zstd = "0.11.2"

[dependencies.serde]
version = "1.0.137"
features = ["derive"]
